#1003 error when apply 3 d to empty canvas
epam/ketcher pull request #1034
Opened 2021-11-26 15:14 UTC by Alex-Work-Account

2021-11-29 06:56 UTC, AnaMoskvina approved these changes

2021-11-29 09:43 UTC, AndreiMazol commented on packages/ketcher-react/src/script/ui/state/shared.js
> +          if (!struct) {
It looks like workaround. I guess 'then' expression  should be only executed if struct is not empty. Could you  find the reason of this case?

2021-11-29 09:44 UTC, AndreiMazol reviewed
need to  discuss

2021-11-29 09:44 UTC, AndreiMazol requested changes
see comments

2021-12-01 13:51 UTC, karen-sarkisyan approved these changes

2021-12-01 15:58 UTC, AndreiMazol requested changes
you  should not return hardcoded cml file.

2021-12-01 16:15 UTC, AndreiMazol approved these changes

2021-12-01 16:16 UTC, merged