#1021 redesign the floating windows - functional groups window
epam/ketcher pull request #1035
Opened 2021-11-26 15:23 UTC by AnaMoskvina

Change grid layout and background color of items in TemplateLable, update EmptySearchResult view

Current result:
![Functional_group](https://user-images.githubusercontent.com/77681522/143601883-4b0968c0-2117-4697-b6ca-856164b1b286.PNG)
![Template_library](https://user-images.githubusercontent.com/77681522/143601903-611342e5-ebe5-404f-b9ea-18ddae97f9bf.PNG)
![not_found](https://user-images.githubusercontent.com/77681522/143602149-1f03bf7f-29fe-4da0-822a-c0e123482bd1.PNG)

2021-11-29 09:41 UTC, AndreiMazol requested changes

2021-11-29 09:41 UTC, AndreiMazol commented on packages/ketcher-react/src/icons/index.tsx
> +  'not-found': NotFound
Please follow naming convention

2021-11-29 09:41 UTC, AndreiMazol commented on packages/ketcher-react/src/script/ui/dialog/template/TemplateTable.tsx
> +  const ITEM_SIZE = { width: 100, height: 100 }
Could you move it into less file?

2021-11-29 12:15 UTC, AnaMoskvina commented on packages/ketcher-react/src/icons/index.tsx
> +  'not-found': NotFound
renamed

2021-11-29 12:15 UTC, AnaMoskvina commented on packages/ketcher-react/src/script/ui/dialog/template/TemplateTable.tsx
> +  const ITEM_SIZE = { width: 100, height: 100 }
done

2021-12-01 08:49 UTC, AndreiMazol approved these changes

2021-12-01 08:49 UTC, merged