#1044 Text Tool: Add special symbols
epam/ketcher pull request #1048
Opened 2021-12-01 09:50 UTC by r1z3rISGOD

2021-12-02 14:46 UTC, AndreiMazol requested changes

2021-12-02 14:46 UTC, AndreiMazol commented on packages/ketcher-react/src/icons/index.tsx
> +import Symbols from './files/symbols.svg'
Please follow naming convention

2021-12-06 13:36 UTC, AnaMoskvina commented on packages/ketcher-react/src/script/ui/views/modal/components/Text/SpecialSymbols/SpecialSymbolsButton.module.less
> +.textButton {
Would be nice to re-use styles, as styles in TextButton.module.less are basically identical

2021-12-09 12:16 UTC, AndreiMazol approved these changes

2021-12-09 12:16 UTC, merged