#1093 Fix templates tool aromatic attachment
epam/ketcher pull request #1099
Opened 2021-12-15 07:09 UTC by karen-sarkisyan

Fixes bug #1093  that I introduced in PR #1064

2021-12-15 13:26 UTC, AndreiMazol commented on packages/ketcher-react/src/script/editor/tool/template.ts
> +      const frIds = molecule.getFragmentIds(frid as number)
frid can be undefined here

2021-12-15 13:27 UTC, AndreiMazol requested changes
need to discuss

2021-12-16 14:28 UTC, AndreiMazol requested changes
need to  discuss: this case should be covered by aromaticFusing.ts

2021-12-16 15:37 UTC, karen-sarkisyan commented
Closing PR because changes that introduced the bug have been reverted.

2021-12-16 15:37 UTC, closed without merging