#1105 Implement Redux for ketcher-polymer-editor-react and create Layout component
epam/ketcher pull request #1121
Opened 2021-12-17 12:26 UTC by ViktoriiaFedotkina

2021-12-17 14:17 UTC, AndreiMazol requested changes

2021-12-17 14:17 UTC, AndreiMazol commented on packages/ketcher-react/src/script/ui/action/index.js
> +    'This action is unavailable via layout.\n' + // eslint-disable-line no-undef
Why did you update this message?

2021-12-22 08:50 UTC, AnaMoskvina approved these changes

2021-12-22 10:15 UTC, AndreiMazol approved these changes

2021-12-23 08:13 UTC, merged