#1146 create rap switcher components
epam/ketcher pull request #1155
Opened 2021-12-27 10:18 UTC by Alex-Work-Account

2022-01-13 12:33 UTC, ViktoriiaFedotkina commented on packages/ketcher-polymer-editor-react/src/components/rna/Switcher/Switcher.test.tsx
> +  render(
you can use render from 'test-utils', it's already wrapped in themeProvider

2022-01-13 12:36 UTC, ViktoriiaFedotkina commented on packages/ketcher-polymer-editor-react/src/components/monomerLibrary/MonomerLibrary.tsx
> +      // props: { list: [{ name: 'R' }, { name: 'N' }, { name: 'A' }] }
forgot to remove?

2022-01-13 13:35 UTC, ViktoriiaFedotkina approved these changes

2022-01-18 08:10 UTC, AndreiMazol requested changes
tests should be changed

2022-01-24 08:39 UTC, ViktoriiaFedotkina approved these changes

2022-01-24 10:41 UTC, karen-sarkisyan commented on packages/ketcher-polymer-editor-react/src/components/rna/Switcher/Switcher.tsx
> +    >
It's up to you if you want to change it, but as long as we wanted to minimize inline `css` styles, you could write this component like this:

```tsx
...
import { useTheme, css } from '@emotion/react'
...
const RAPButton = ({ isActive, children, callback }: RAPButtonProps) => {

  const { color } = useTheme()

  const styles = css`
    padding: 3px 12px;
    background-color: ${isActive
      ? color.button.primary.active
      : color.background.canvas};
    border-radius: 8px;
    line-height: 18px;
    min-width: 33px;
    color: ${isActive ? color.text.light : color.text.dark};
    :hover {
      background-color: ${color.button.primary.hover};
      color: ${color.text.light};
    }
  `

  return (
    <Button css={styles} onClick={callback}>
      {children}
    </Button>
  )
}
```

2022-01-25 06:56 UTC, ElenaOdnoshivkina approved these changes

2022-01-25 08:08 UTC, AndreiMazol approved these changes

2022-01-25 08:09 UTC, merged