#1197 Get or Set settings data when using ketcher-react
epam/ketcher pull request #1210
Opened 2022-01-27 10:01 UTC by ElenaOdnoshivkina

2022-01-27 15:25 UTC, AndreiMazol requested changes
need to  discuss

2022-02-09 12:54 UTC, AndreiMazol commented on packages/ketcher-core/src/domain/services/storage/storage.types.ts
> +  set: (data: RecordOrArrayOfRecords, key: string) => Promise<any>
set/get should be generics

2022-02-09 12:55 UTC, AndreiMazol requested changes
need to discuss

2022-02-09 12:55 UTC, AndreiMazol commented on packages/ketcher-react/src/script/builders/ketcher/KetcherBuilder.ts
> +    this.storage = undefined
?

2022-02-09 12:55 UTC, AndreiMazol commented on packages/ketcher-react/src/script/builders/ketcher/KetcherBuilder.ts
> +    storage?: StorageProvider
use correct variable names

2022-07-06 18:53 UTC, Mariia-Katkova commented
In 2.5 you can save settings already

2023-09-14 11:49 UTC, closed without merging