#1240 Create Open file modal window
epam/ketcher pull request #1244
Opened 2022-02-09 06:32 UTC by ElenaOdnoshivkina

2022-02-11 07:02 UTC, ViktoriiaFedotkina commented on packages/ketcher-polymer-editor-react/src/components/shared/actionButton/ActionButton.tsx
> +
you can add some baseStyle object and move identical css props there

2022-02-11 07:11 UTC, ViktoriiaFedotkina commented on packages/ketcher-polymer-editor-react/src/components/modal/Open/OpenContainer.tsx
> +const OpenContainer = ({ isModalOpen, onClose }) => {
this container can be removed

2022-02-14 07:46 UTC, ViktoriiaFedotkina approved these changes

2022-02-14 13:26 UTC, karen-sarkisyan requested changes

2022-02-14 13:26 UTC, karen-sarkisyan commented on packages/ketcher-polymer-editor-react/src/Editor.tsx
>    }
I don't think it's a good idea. For one, it sets active tool to 'Open', but there's no such tool. We should have some separation of this logic, and it probably should be handled inside of `Editor`.

2022-02-14 14:44 UTC, karen-sarkisyan requested changes

2022-02-14 14:44 UTC, karen-sarkisyan commented on packages/ketcher-polymer-editor-react/src/components/modal/Open/TextEditor/TextEditor.tsx
> +export const TextEditor = ({ structStr, inputHandler }: TextEditorProps) => {
Maybe we should have a shared styled textarea component, same one we create for Save modal? https://github.com/epam/ketcher/pull/1246/files#diff-29ff483d977e475e9b6e4578a4b165776d0c3f268c75f2d8a5cc6140b78b0b32

2022-02-17 08:21 UTC, karen-sarkisyan requested changes

2022-02-17 08:21 UTC, karen-sarkisyan commented on packages/ketcher-polymer-editor-react/package.json
> +    "@testing-library/dom": "^8.11.3",
This should be in devDependencies :)

2022-02-17 10:12 UTC, karen-sarkisyan approved these changes

2022-02-18 09:42 UTC, merged