#1239 create save file modal window
epam/ketcher pull request #1246
Opened 2022-02-10 11:37 UTC by ViktoriiaFedotkina

2022-02-11 08:28 UTC, ElenaOdnoshivkina approved these changes

2022-02-14 14:15 UTC, karen-sarkisyan requested changes

2022-02-14 14:15 UTC, karen-sarkisyan commented on packages/ketcher-polymer-editor-react/src/components/shared/inputField/InputField.tsx
> +export const InputField = ({ value, id, onChange, label, ...rest }: Props) => {
`InputField` name seems a little too generic for this. Maybe let's call it `TextInputField`?

2022-02-14 14:20 UTC, ViktoriiaFedotkina commented on packages/ketcher-polymer-editor-react/src/theming/defaultTheme/theme.types.ts
> +        rested: string
well they are now used in figma. Inactive is disabled, rested is not active but is not disabled as well

2022-02-14 14:28 UTC, ViktoriiaFedotkina commented on packages/ketcher-polymer-editor-react/src/components/shared/actionButton/ActionButton.tsx
> +      {children || label}
I used this here [packages/ketcher-polymer-editor-react/src/components/modal/save/Save.tsx](https://github.com/epam/ketcher/pull/1246/files#diff-58b0b1e585a5199bccbe910f5482833ffdbd311062a5f73b3d05dda47e1c49fb) (192)

2022-02-14 14:39 UTC, karen-sarkisyan commented on packages/ketcher-polymer-editor-react/src/components/shared/actionButton/ActionButton.tsx
> +      {children || label}
Oh, right, didn't see it. Fair enough 👍

2022-02-14 15:08 UTC, karen-sarkisyan commented on packages/ketcher-polymer-editor-react/src/theming/defaultTheme/theme.types.ts
> +        rested: string
You're right. Still, it seems incorrect. I've discussed this with our colleagues, they'll rename input states soon.

2022-02-15 07:58 UTC, karen-sarkisyan approved these changes

2022-02-15 11:29 UTC, AndreiMazol approved these changes

2022-02-15 11:29 UTC, merged