#1257 An error in console when selecting the Bond Tool after closing the 'Enhanced Stereochemistry' window
epam/ketcher pull request #1264
Opened 2022-02-17 06:49 UTC by ElenaOdnoshivkina

2022-02-17 14:25 UTC, karen-sarkisyan requested changes

2022-02-17 14:25 UTC, karen-sarkisyan commented on packages/ketcher-react/src/script/editor/tool/enhanced-stereo.ts
> +    this.isNotActiveTool = true
That works, but maybe let's make it even more obvious? It should never be an active tool, so let's make it always true:

```typescript
class EnhancedStereoTool {
  editor: Editor
  stereoAtoms: Array<number>
  isNotActiveTool: true

  constructor(editor) {
    const selection = editor.selection()
    this.editor = editor
    this.isNotActiveTool = true
...
```

And we can remove all the other lines with `this.isNotActiveTool = true` after that.

2022-02-17 15:20 UTC, karen-sarkisyan approved these changes

2022-02-18 09:39 UTC, AndreiMazol approved these changes

2022-02-18 09:39 UTC, merged