#1292 Incorrect horizontal scrollbars in save structure modal window
epam/ketcher pull request #1296
Opened 2022-03-02 09:04 UTC by AnaMoskvina

- get rid of redundant scrollbars
- apply unified font for textarea
- add rule for scrollbars for mozilla

2022-03-02 13:50 UTC, karen-sarkisyan requested changes
I think that besides preventing overflows maybe let's also fix style of a horizontal scrollbar, in case it happens to appear somewhere?

We only need to set its height (same as width when it's vertical) in `mixins.less`:

```diff

  &::-webkit-scrollbar {
    width: 4px;
+   height: 4px;
    background-color: @color-scroll-inactive;
    border-radius: 2px;
    -webkit-border-radius: 2px;
  }

```
So horizontal scrollbars would be thin too:
![image](https://user-images.githubusercontent.com/18420141/156374101-fccc8f55-ddeb-41d6-9c1a-aff161985ffd.png)

2022-03-02 17:13 UTC, karen-sarkisyan requested changes

2022-03-02 17:13 UTC, karen-sarkisyan commented on packages/ketcher-react/src/script/ui/views/modal/components/document/Save/Save.module.less
>      height: fit-content;
As of now, even 1 line of warnings causes overflow.
![image](https://user-images.githubusercontent.com/18420141/156412610-c7e817d6-954a-45d5-a857-2912454e70c1.png)

I suggest that we avoid unnecessary overflow and scroll when we're within `50px` of max-height by using this code or something like it:
```diff
.warnings {
  max-height: 50px;
- height: fit-content;
+ flex-shrink: 0;
  border: none;
  border-radius: 4px;
  margin: 2px 0;
  padding: 2px 5px;
  overflow: auto;
```

2022-03-03 09:53 UTC, karen-sarkisyan approved these changes

2022-03-03 13:30 UTC, AndreiMazol approved these changes

2022-03-03 13:30 UTC, merged