#46 The structures with atoms with valences rendering incorrectly after saving
epam/ketcher pull request #164
Opened 2020-12-10 11:51 UTC by Aniuta907

2020-12-11 08:52 UTC, Aniuta907 commented
<img width="331" alt="valence" src="https://user-images.githubusercontent.com/40429134/101882726-51082e80-3ba7-11eb-9d41-c5a1de77462a.png">
<img width="331" alt="valence2" src="https://user-images.githubusercontent.com/40429134/101882735-549bb580-3ba7-11eb-8399-767be8e2093c.png">

2020-12-11 09:09 UTC, AndreiMazol requested changes
warnings should be rendered one by one in a column (see 2th screenshot)

2020-12-13 17:27 UTC, Aniuta907 commented
<img width="319" alt="Untitled" src="https://user-images.githubusercontent.com/40429134/102018930-7781c180-3d81-11eb-8305-395ee34bab95.png">

2020-12-14 08:17 UTC, AndreiMazol approved these changes

2020-12-14 08:18 UTC, merged