#2276 Click & drag an 'Atom' on FG, Salts and Solvents, FG connected with Atom forms many atoms
epam/ketcher pull request #2577
Opened 2023-05-05 14:06 UTC by VasilevDO

Closes #2276 
Changes:
1) Atom tool "click and drag" action works as expected now
2) If the user clicks and drags an atom out of the original target, and then hovers back over the original target, the bond action will revert (after the 'mouseup' event, it will trigger a replace action)

2023-05-06 06:14 UTC, yuleicul commented
Hi @VasilevDO , it looks really cool to me in the sense that the bond action will revert after hovering back! 👍 

Unfortunately, I found a small problem which seems not to behave correctly, according to 
> **Expected behavior**
> ...
> For Salt and Solvents: Atom appears where the left mouse button was **released without a connection**
> ...

![code-review-2276](https://user-images.githubusercontent.com/27288153/236605685-f29ac12c-2ed5-4dca-a71d-5cab49c3a9ad.gif)

2023-05-06 06:15 UTC, yuleicul requested changes
Hi @VasilevDO , it looks really cool to me in the sense that the bond-adding action will be reverted after hovering back! 👍 

Unfortunately, I found a small problem which seems not to behave correctly, according to 
> **Expected behavior**
> ...
> For Salt and Solvents: Atom appears where the left mouse button was **released without a connection**
> ...

![code-review-2276](https://user-images.githubusercontent.com/27288153/236605685-f29ac12c-2ed5-4dca-a71d-5cab49c3a9ad.gif)

2023-05-08 10:12 UTC, AnastasiiaPlyako commented on packages/ketcher-react/src/script/editor/tool/atom.ts
> +          FunctionalGroup.isContractedFunctionalGroup(ci.id, functionalGroups)
that's fun that I have the same logic in my PR  :) I think we need to extract this into a separate function and reuse it. 
https://github.com/epam/ketcher/pull/2580/files#diff-ee62e3d2a7eb8e9230e2d13e3cfe44e4ea9ea805a61f971355d38aab66dda856R62

2023-05-08 10:47 UTC, AnastasiiaPlyako commented on packages/ketcher-react/src/script/editor/tool/atom.ts
> +        ? molecule.functionalGroups.get(ci?.id)?.name
could we write here "ci?.map === 'functionalGroups' && molecule.functionalGroups.get(ci?.id)?.name"?

2023-05-12 03:59 UTC, yuleicul commented
Just a kind reminder, please remember to click 're-request review' after your code is ready again 😃

2023-05-12 04:04 UTC, yuleicul approved these changes

2023-05-16 12:55 UTC, merged