#85 migrate circle to ellipse + refactor to ts
epam/ketcher pull request #286
Opened 2021-02-04 12:34 UTC by ensemenova

2021-02-05 10:19 UTC, TomasLight requested changes

2021-02-05 10:19 UTC, TomasLight commented on packages/ketcher-react/src/script/editor/operations/simpleObject.ts
> +    const ret = new SimpleObjectAdd()
please rename `ret` to `simpleObject`

2021-02-05 10:19 UTC, TomasLight commented on packages/ketcher-react/src/script/editor/operations/simpleObject.ts
> +    d: any
what is it?

2021-02-05 10:19 UTC, TomasLight commented on packages/ketcher-react/src/script/editor/operations/simpleObject.ts
> +    d: any
same

2021-02-05 10:19 UTC, TomasLight commented on packages/ketcher-react/src/script/editor/operations/simpleObject.ts
> +    if (item.mode === SimpleObjectMode.ellipse) {
too much if-statements

2021-02-05 10:19 UTC, TomasLight commented on packages/ketcher-react/src/script/editor/operations/simpleObject.ts
> +import Vec2 from '../../util/vec2'
add copyright

2021-02-05 10:19 UTC, TomasLight commented on packages/ketcher-react/src/script/chem/struct/simpleObject.ts
> +import Vec2 from '../../util/vec2'
add copyright

2021-02-05 10:19 UTC, TomasLight commented on packages/ketcher-react/src/script/format/chemGraph/fromGraph/simpleObjectToStruct.ts
> + * Copyright 2020 EPAM Systems
update year

2021-02-05 10:19 UTC, TomasLight commented on packages/ketcher-react/src/script/format/chemGraph/fromGraph/simpleObjectToStruct.ts
> +  let object =
const

2021-02-05 14:03 UTC, ensemenova commented on packages/ketcher-react/src/script/editor/operations/simpleObject.ts
> +    struct.simpleObjectSetPos(
This method has 2 params id and pos. Id for selecting exact simple object from all and pos to set

2021-02-08 09:00 UTC, ensemenova commented on packages/ketcher-react/src/script/editor/actions/simpleobject.ts
> +  d,
not very clearly, it's some kind of diff in position

2021-02-08 09:08 UTC, ensemenova commented on packages/ketcher-react/src/script/chem/struct/simpleObject.ts
> +import Vec2 from '../../util/vec2'
done

2021-02-08 13:11 UTC, closed without merging