#2817 Rotation tool: cancel rotation by pressing 'right click' button
epam/ketcher pull request #2892
Opened 2023-07-07 10:12 UTC by Inga-Vishnivetskaia

## How the feature works? / How did you fix the issue?

- the rotation should is cancelled and the structure revert to the original position it was in when rotation was started
- the structure stays selected

[video: Cancel Rotate on right click](https://clipchamp.com/watch/ymYauyz09bW)

## Check list
- [ ] unit-tests written
- [ ] e2e-tests written
- [x] documentation updated
- [x] PR name follows the pattern `#1234 – issue name`
- [ ] branch name doesn't contain '#'
- [x] PR is linked with the issue
- [x] base branch (master or release/xx) is correct

2023-07-11 07:10 UTC, yuleicul commented on packages/ketcher-react/src/script/ui/state/mouse.ts
> +          rightClickHandle(getState)
I'd suggest naming function starting with verb, how about `handleRightClick`

2023-07-11 07:10 UTC, yuleicul commented on packages/ketcher-react/src/script/ui/views/components/ContextMenu/ContextMenuTrigger.tsx
> +        if (selection && !isLeftMouseButtonPressed) {
It takes a while to think why `isLeftMouseButtonPressed` is needed. Maybe we can:
```suggestion
        const isLeftMouseButtonPressed = event.buttons === 1
        const isRotationReverted = isLeftMouseButtonPressed
        if (selection && !isRotationReverted) {
```

2023-07-11 11:08 UTC, yuleicul commented on packages/ketcher-react/src/script/ui/state/mouse.ts
> +      },
Please remember to remove this listener

2023-07-12 08:16 UTC, Nitvex commented on ketcher-autotests/tests/Structure-Creating-&-Editing/Actions-With-Structures/Rotation/rotation.spec.ts
> +    const snapshotBeforeRotation = await editor.screenshot();
for this we have a helper `takeEditorScreenshot`

2023-07-13 09:21 UTC, Nitvex requested changes

2023-07-13 09:21 UTC, Nitvex commented on ketcher-autotests/tests/utils/clicks/selectButtonByTitle.ts
> +  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
Can we fix this warning?
Previously, we had two different repos and it wasn't easy to make changes simultaneously in both repos. But errors like that should be easily fixed now.

2023-07-13 09:21 UTC, Nitvex commented on ketcher-autotests/tests/Structure-Creating-&-Editing/Actions-With-Structures/Rotation/rotation.spec.ts
> +    const snapshotBeforeRotation = await getEditorScreenshot(page);
I don't understand this test. First of all, why do you need to choose `selectSingleBondTool`?
Secondly, you do literally nothing with the structure. 
1) You get coordinates of rotation handle
2) Then you click on it – no action is performed on the structure
3) Then you move mouse to some coordinates (may be worth renaming them to something like `COORDINATES_TO_PERFORM_ROTATION`)
4) And then make a right click.

This way, test is supposed to be:
1) You get coordinates of rotation handle.
2) `mousedown` on rotation handle, not click
3) Move mouse to some coordinates (you need to drag handle, not simply click on it)
4) Press right click

2023-07-13 09:21 UTC, Nitvex commented on ketcher-autotests/tests/Structure-Creating-&-Editing/Actions-With-Structures/Rotation/rotation.spec.ts
> +    expect(snapshotBeforeRotation).toEqual(snapshotAfterRotation);
Could you figure out, why did we get an empty screenshot?

2023-07-14 14:11 UTC, AleksandraSmolianinova approved these changes
Previewed. No cooments

2023-07-14 14:16 UTC, Nitvex approved these changes

2023-07-14 14:16 UTC, merged