3047 13 tests for floating windows
epam/ketcher pull request #3080
Opened 2023-08-10 11:26 UTC by Vehemen

## How the feature works? / How did you fix the issue?
(Screenshots, videos, or GIFs, if applicable)

## Check list
- [ ] unit-tests written
- [ ] e2e-tests written
- [ ] documentation updated
- [ ] PR name follows the pattern `#1234 – issue name`
- [ ] branch name doesn't contain '#'
- [ ] PR is linked with the issue
- [ ] base branch (master or release/xx) is correct
- [ ] task status changed to "Code review"

2023-08-22 10:55 UTC, rrodionov91 requested changes

2023-08-22 10:55 UTC, rrodionov91 commented on example/package.json
> +    "serve": "^14.2.0",
I'm not sure that we need to update libraries. Could you please explain why it was done?

2023-08-22 10:55 UTC, rrodionov91 commented on ketcher-autotests/tests/User-Interface/Floating windows/floating-windows.spec.ts
> +    );
Could you please move it to separate file because it is test data?

2023-08-22 10:56 UTC, rrodionov91 commented
And resolve conflicts please

2023-09-21 11:47 UTC, Zhirnoff commented
Tests from this pull request have been moved to the pull request https://github.com/epam/ketcher/pull/3343

2023-09-21 11:47 UTC, closed without merging