#3075 - Replaced aromatize and dearomatize icons
epam/ketcher pull request #3116
Opened 2023-08-15 10:19 UTC by chgayane

## How the feature works? / How did you fix the issue?
(Screenshots, videos, or GIFs, if applicable)

## Check list
- [ ] unit-tests written
- [ ] e2e-tests written
- [ ] documentation updated
- [x] PR name follows the pattern `#1234 – issue name`
- [x] branch name doesn't contain '#'
- [x] PR is linked with the issue
- [x] base branch (master or release/xx) is correct
- [x] task status changed to "Code review"

2023-08-16 06:05 UTC, flange-ipb commented
@chgayane 
I have the feeling that the icons are mixed up.

2023-08-21 08:35 UTC, AnastasiyaPiatrovaKlu approved these changes

2023-08-22 11:34 UTC, rrodionov91 requested changes

2023-08-22 11:34 UTC, rrodionov91 commented on ketcher-autotests/tests/File-Management/Open-And-Save-Files/cdxml-files.spec.ts-snapshots/Tests-for-API-setMolecule-getMolecule-Function-7c4e9-ml-file-with-contracted-and-expanded-function-1-chromium-linux.png
Looks like it should not be expanded. Same on several screenshots below.

2023-08-22 11:59 UTC, closed without merging