#2994 - Attachment points should be within S-Group brackets
epam/ketcher pull request #3232
Opened 2023-08-31 13:21 UTC by Nitvex

## How the feature works? / How did you fix the issue?
(Screenshots, videos, or GIFs, if applicable)

## Check list
- [ ] unit-tests written
- [ ] e2e-tests written
- [ ] documentation updated
- [ ] PR name follows the pattern `#1234 – issue name`
- [ ] branch name doesn't contain '#'
- [ ] PR is linked with the issue
- [ ] base branch (master or release/xx) is correct
- [ ] task status changed to "Code review"
- [ ] reviewers are notified about the pull request

2023-08-31 16:33 UTC, Zhirnoff commented
I guess that for Multiple group the "Repeat count" numbers indication should be positioned on the lower right side of the brackets. Not in the right upper side. The rest of the brackets are also incorrectly displayed. The example on the left is correct
![2023-08-31_18h46_13](https://github.com/epam/ketcher/assets/62464241/39bb2f5b-e9e6-4a48-b466-3eea22c7d6e4)
![2023-08-31_18h55_25](https://github.com/epam/ketcher/assets/62464241/56647b95-dcc0-438d-9c7a-9190a7273a18)
![2023-08-31_19h02_20](https://github.com/epam/ketcher/assets/62464241/c3518054-1f8e-4f05-b5df-f9017ef0aada)
![2023-08-31_19h07_04](https://github.com/epam/ketcher/assets/62464241/dc8cad59-7fff-47c6-a553-8a56ceea3845)

2023-09-14 11:25 UTC, rrodionov91 requested changes

2023-09-14 11:25 UTC, rrodionov91 commented on packages/ketcher-core/src/application/render/draw.ts
> +    a1 = bondCenter.addScaled(bracketDirection, 0.5 * bracketHeight);
is it possible to name these magic numbers somehow? And also it would be great to rename a0/a1/... to something more meaningful.

2023-09-14 11:25 UTC, rrodionov91 commented on packages/ketcher-core/src/application/render/restruct/resgroup.ts
> +        brackets[ir].bracketAngleDirection.y > bracket.bracketAngleDirection.y)
Could you please rename "ir" if you know what is it?

2023-09-14 11:25 UTC, rrodionov91 commented on packages/ketcher-core/src/application/render/restruct/resgroup.ts
> +            util.shiftRayBox(cc, bracketDirectionNegated, boundingBox),
Could you please rename tl/tr/tt/... ?

2023-09-14 11:25 UTC, rrodionov91 commented on packages/ketcher-core/src/application/render/restruct/resgroup.ts
>      (function () {
Why this code in if else statements is wrapper to IIFE?

2023-09-14 11:28 UTC, rrodionov91 requested changes

2023-09-15 09:30 UTC, rrodionov91 requested changes
Could you please check this scenario? I think it is a bug.
https://github.com/epam/ketcher/assets/14859362/b4ff41d1-65bc-428a-b5cb-410a2a27fcb3

2023-09-15 10:40 UTC, rrodionov91 approved these changes

2023-09-15 11:15 UTC, merged