[DRAFT] #3129 - Full template preview following mouse cursor
epam/ketcher pull request #3252
Opened 2023-09-05 07:38 UTC by KonstantinEpam23

## How the feature works? / How did you fix the issue?
(Screenshots, videos, or GIFs, if applicable)

## Check list
- [ ] unit-tests written
- [ ] e2e-tests written
- [ ] documentation updated
- [ ] PR name follows the pattern `#1234 – issue name`
- [ ] branch name doesn't contain '#'
- [ ] PR is linked with the issue
- [ ] base branch (master or release/xx) is correct
- [ ] task status changed to "Code review"
- [ ] reviewers are notified about the pull request

2023-09-07 09:57 UTC, KonstantinEpam23 commented
The current issue is that after selecting the template - if the user presses undo - the template preview will be left on the canvas instead of hiding the preview and undoing the last action.

I have started re-doing the approach in branch: `3129-full-template-preview-following-mouse-cursor-draft-4`

2023-09-20 12:21 UTC, nanoblit commented on packages/ketcher-react/src/script/editor/tool/templatePreview.ts
> +type CiType = { map: string; id: number; dist: number };
What's "ci"? Maybe we can use the full name?

2023-09-20 14:27 UTC, Zhirnoff commented
16 tests fail. Please add screenshots of local run

2023-09-21 12:07 UTC, rrodionov91 requested changes
Please check this behaviour. Looks like bugs.

https://github.com/epam/ketcher/assets/14859362/d2fa9555-16a7-46c2-a8c9-744e05b8711a



https://github.com/epam/ketcher/assets/14859362/be7c7b50-cf3d-4150-8647-96755893d332


https://github.com/epam/ketcher/assets/14859362/d696d0b3-b572-4559-9b09-feb1f518b4f9

2023-09-25 14:37 UTC, Zhirnoff commented
Pre-tested. Bug is fixed. And fixed comments added by @rrodionov91

2023-09-26 11:57 UTC, rrodionov91 approved these changes

2023-09-26 11:57 UTC, rrodionov91 commented on ketcher-autotests/tests/User-Interface/Preview-For-Abbreviated-Structures/preview-for-abbreviated-structures.spec.ts
> +    await takeEditorScreenshot(page);
I believe that this test covers the case from the previous one and we can keep just only this test.

2023-09-26 11:57 UTC, rrodionov91 commented on packages/ketcher-react/src/script/editor/tool/templatePreview.ts
> +  private readonly mode: 'fg' | null;
I believe we can have more clear values for "mode".

2023-09-26 11:57 UTC, rrodionov91 commented on packages/ketcher-react/src/script/editor/tool/templatePreview.ts
> +    const ci = this.getPreviewTarget();
I would propose to rename ci to previewTarget

2023-09-26 11:57 UTC, rrodionov91 commented on packages/ketcher-react/src/script/editor/tool/templatePreview.ts
> +      ci && !this.connectedPreviewAction && !this.connectedPreviewTimeout;
I would propose to rename it to shouldHideConnectedPreview and shouldShowConnectedPreview

2023-09-26 11:57 UTC, rrodionov91 commented on packages/ketcher-react/src/script/editor/tool/templatePreview.ts
> +      }
I would propose to move it to separate function f.e. moveFloatingPreview()

2023-09-26 15:40 UTC, merged