Autotests: #3318 - Create autotests for attachment point tool
epam/ketcher pull request #3363
Opened 2023-09-26 09:51 UTC by MartaWilliams

## How the feature works? / How did you fix the issue?
(Screenshots, videos, or GIFs, if applicable)

## Check list
- [ ] unit-tests written
- [ ] e2e-tests written
- [ ] documentation updated
- [ ] PR name follows the pattern `#1234 – issue name`
- [ ] branch name doesn't contain '#'
- [ ] PR is linked with the issue
- [ ] base branch (master or release/xx) is correct
- [ ] task status changed to "Code review"
- [ ] reviewers are notified about the pull request

2023-09-26 10:09 UTC, chgayane approved these changes

2023-09-26 11:07 UTC, Nitvex requested changes

2023-09-26 11:07 UTC, Nitvex commented on ketcher-autotests/tests/Structure-Creating-&-Editing/Actions-With-Structures/Attachment-Point-Tool/actions-with-attachment-point-tool.spec.ts
> +  // test.afterEach(async ({ page }) => {
Could you remove this comment or uncomment this line?

2023-09-26 11:07 UTC, Nitvex commented on ketcher-autotests/tests/Structure-Creating-&-Editing/Actions-With-Structures/Attachment-Point-Tool/actions-with-attachment-point-tool.spec.ts
> +    // check that structure opened from file is displayed correctly
You can remove this comment it is pretty self-explanatory

2023-09-26 11:07 UTC, Nitvex commented on ketcher-autotests/tests/Structure-Creating-&-Editing/Actions-With-Structures/Attachment-Point-Tool/actions-with-attachment-point-tool.spec.ts
> +    await openFileAndAddToCanvas('KET/test-EPMLSOPKET-18025.ket', page);
Can you give more meaningful names for files? Which structure is stored in the file?

2023-10-04 07:56 UTC, chgayane approved these changes

2023-10-04 14:35 UTC, ViktoriaTkacheva approved these changes

2023-10-06 06:58 UTC, Nitvex commented on ketcher-autotests/tests/test-data/Molfiles-V2000/test-EPMLSOPKET-18025.mol
> +
This file doesn't seem to be used, can you remove it?

2023-10-09 14:07 UTC, Nitvex approved these changes

2023-10-09 14:07 UTC, merged