#3385 - Macro: Overlapping of bonds between 2 monomers
epam/ketcher pull request #3453
Opened 2023-10-17 08:01 UTC by chgayane

## How the feature works? / How did you fix the issue?
(Screenshots, videos, or GIFs, if applicable)

## Check list
- [ ] unit-tests written
- [ ] e2e-tests written
- [ ] documentation updated
- [ ] PR name follows the pattern `#1234 – issue name`
- [ ] branch name doesn't contain '#'
- [ ] PR is linked with the issue
- [ ] base branch (master or release/xx) is correct
- [ ] task status changed to "Code review"
- [ ] reviewers are notified about the pull request

2023-10-17 11:57 UTC, Nitvex requested changes

2023-10-17 11:57 UTC, Nitvex commented on packages/ketcher-core/src/application/editor/tools/Bond.ts
> +      for (const key in secondMonomer.attachmentPointsToBonds) {
I believe `key` here is attachmentPoint right?

2023-10-17 11:57 UTC, Nitvex commented on packages/ketcher-core/src/application/editor/tools/Bond.ts
> +        if (bond !== null) {
I propose to simplify
```
if (!bond) {
  continue;
}

const alreadyHasBond = 
             (bond.firstMonomer === firstMonomer &&
              bond.secondMonomer === secondMonomer) ||
             (bond.firstMonomer === secondMonomer &&
              bond.secondMonomer === firstMonomer)
if (alreadyHasBond) {
          this.editor.events.error.dispatch(
              "There can't be more than 1 bond between the first and the second monomer",
            );
            return;
}
```

2023-10-18 01:43 UTC, StarlaStarla approved these changes

2023-10-18 11:35 UTC, MartaWilliams commented
Tested 
![2023-10-18_13h08_25](https://github.com/epam/ketcher/assets/82752700/e753384f-2012-405b-866f-bd30e03115bb)

2023-10-18 14:26 UTC, Nitvex approved these changes

2023-10-18 14:26 UTC, merged