Autotests: # 3464 - Ignore chiral flag
epam/ketcher pull request #3468
Opened 2023-10-19 11:22 UTC by MartaWilliams

## How the feature works? / How did you fix the issue?
(Screenshots, videos, or GIFs, if applicable)

## Check list
- [ ] unit-tests written
- [ ] e2e-tests written
- [ ] documentation updated
- [ ] PR name follows the pattern `#1234 – issue name`
- [ ] branch name doesn't contain '#'
- [ ] PR is linked with the issue
- [ ] base branch (master or release/xx) is correct
- [ ] task status changed to "Code review"
- [ ] reviewers are notified about the pull request

2023-10-19 14:16 UTC, OlgaMazurina approved these changes

2023-10-19 14:16 UTC, OlgaMazurina commented on ketcher-autotests/tests/Settings/Stereochemistry/ignore-chiral-flag.spec.ts
> +    const pointx = 204;
for constants it is right to use lowerCamelCase
so I suggest to use 'pointX' here

2023-10-19 14:16 UTC, OlgaMazurina commented on ketcher-autotests/tests/Settings/Stereochemistry/ignore-chiral-flag.spec.ts
> +    const pointy = 211;
```suggestion
    const pointY = 211;
```

2023-11-01 10:15 UTC, Zhirnoff approved these changes

2023-11-01 10:16 UTC, Zhirnoff commented
Take a look at failing tests.
![2023-11-01_13h15_54](https://github.com/epam/ketcher/assets/62464241/e5726815-385d-42d1-94eb-e60d35e2ad6c)

2023-11-01 10:17 UTC, Zhirnoff reviewed
Take a look at failing tests please

2023-11-01 10:19 UTC, Zhirnoff requested changes
Take a look at failing tests.

2023-11-09 10:03 UTC, StarlaStarla commented on ketcher-autotests/tests/Settings/Stereochemistry/ignore-chiral-flag.spec.ts
> +  await page.mouse.wheel(deltaX, deltaY);
here we could also use the common function to scroll right?

2023-11-13 01:44 UTC, StarlaStarla approved these changes

2024-02-06 15:28 UTC, Zhirnoff approved these changes

2024-02-06 16:49 UTC, merged