Fix template table layout for small screens
epam/ketcher pull request #349
Opened 2021-02-26 09:19 UTC by irinatelnova

2021-02-26 09:48 UTC, ensemenova approved these changes

2021-02-26 12:46 UTC, TomasLight requested changes

2021-02-26 12:46 UTC, TomasLight commented on packages/ketcher-react/src/style/dialogs.less
> +    }
please fix according our discussion

2021-02-26 12:46 UTC, TomasLight commented on packages/ketcher-react/src/style/dialogs.less
> +  }
same

2021-03-09 07:36 UTC, irinatelnova commented on packages/ketcher-react/src/style/dialogs.less
> +    }
@TomasLight fixed

2021-03-09 07:36 UTC, irinatelnova commented on packages/ketcher-react/src/style/dialogs.less
> +  }
@TomasLight fixed

2021-03-09 08:40 UTC, TomasLight approved these changes

2021-03-09 09:57 UTC, AndreiMazol requested changes
delete master features please

2021-03-09 10:52 UTC, closed without merging