#352 Fix React warning messages
epam/ketcher pull request #362
Opened 2021-03-03 08:34 UTC by softcat23

2021-03-03 13:02 UTC, TomasLight requested changes

2021-03-03 13:02 UTC, TomasLight commented on packages/ketcher-react/src/script/ui/views/modal/components/toolbox/RgroupLogic/components/IfThenSelect/IfThenSelect.tsx
> +  Pick<RgroupLogicProps, 'rgroupLabels'>
```
Pick<RgroupLogicProps, 'label'> &
  Pick<RgroupLogicProps, 'rgroupLabels'>
```
to
```
Pick<RgroupLogicProps, 'label' | 'rgroupLabels'>
```

2021-03-03 13:31 UTC, softcat23 commented on packages/ketcher-react/src/script/ui/dialog/toolbox/sdata.jsx
> +          multiple={true}
I thought we need to pass value explicitly, reverted.

2021-03-04 10:24 UTC, TomasLight approved these changes

2021-03-04 11:49 UTC, merged