Macro: #3869 - Left-to-right ("Snake-like") layout for RNA
epam/ketcher pull request #3932
Opened 2024-01-18 14:44 UTC by StarlaStarla

## How the feature works? / How did you fix the issue?
(Screenshots, videos, or GIFs, if applicable)

## Check list
- [ ] unit-tests written
- [ ] e2e-tests written
- [ ] documentation updated
- [ ] PR name follows the pattern `#1234 – issue name`
- [ ] branch name doesn't contain '#'
- [ ] PR is linked with the issue
- [ ] base branch (master or release/xx) is correct
- [ ] task status changed to "Code review"
- [ ] reviewers are notified about the pull request

2024-01-29 18:37 UTC, rrodionov91 requested changes

2024-01-29 18:37 UTC, rrodionov91 commented on packages/ketcher-core/src/application/render/renderers/PolymerBondRenderer.ts
> +    );
I would propose to move part of this logic into concrete monomer classes (Like Peptide, Chem, e t c). Like so for Peptide:

public isMonomerTypeDifferentForChaining(monomerToChain: BaseMonomer) {
  return monomerToChain instanceof Sugar || monomerToChain instanceof Phosphate
}

2024-01-29 18:37 UTC, rrodionov91 commented on packages/ketcher-core/src/domain/entities/DrawingEntitiesManager.ts
> +      45;
I would propose to move 45 into constant with appropriate name

2024-01-29 18:37 UTC, rrodionov91 commented on packages/ketcher-core/src/domain/entities/DrawingEntitiesManager.ts
> +          : polymerBond?.secondMonomer;
there is polymerBond.getAnotherMonomer(rnaBase) method I believe

2024-01-29 18:37 UTC, rrodionov91 commented on packages/ketcher-core/src/domain/entities/DrawingEntitiesManager.ts
> +        45,
Move to constant please.

2024-01-29 18:37 UTC, rrodionov91 commented on packages/ketcher-core/src/domain/entities/DrawingEntitiesManager.ts
> +          45,
Here also

2024-01-30 08:46 UTC, StarlaStarla commented on ketcher-autotests/tests/Macromolecule-editor/Polymer-Bond-Tool/snake-bond-tool.spec.ts
> +    );
It would be great if we could create a separate ticket for this. thanks!

2024-02-01 18:52 UTC, rrodionov91 approved these changes

2024-02-01 18:53 UTC, rrodionov91 requested changes
Please fix comments above

2024-02-02 06:56 UTC, StarlaStarla commented on packages/ketcher-core/src/domain/entities/DrawingEntitiesManager.ts
> +        HORIZONTAL_DISTANCE_FROM_MONOMER +
Actually I just copied the legency code for use. I would assume `DISTANCE_BETWEEN_MONOMERS ` is the length of the corner line that connects two lines of chain,  while the `HORIZONTAL_DISTANCE_FROM_MONOMER ` is the distance between monomers.

2024-02-02 15:17 UTC, merged