3934 support selection entity selection flag in ket format
epam/ketcher pull request #3966
Opened 2024-01-25 15:29 UTC by captain2b

## How the feature works? / How did you fix the issue?
(Screenshots, videos, or GIFs, if applicable)

## Check list
- [ ] unit-tests written
- [ ] e2e-tests written
- [ ] documentation updated
- [ ] PR name follows the pattern `#1234 – issue name`
- [ ] branch name doesn't contain '#'
- [ ] PR is linked with the issue
- [ ] base branch (master or release/xx) is correct
- [ ] task status changed to "Code review"
- [ ] reviewers are notified about the pull request

2024-02-02 16:06 UTC, rrodionov91 requested changes

2024-02-02 16:06 UTC, rrodionov91 commented on packages/ketcher-core/src/domain/entities/struct.ts
> +  }
Could you please leave a comment why we are  blocking these fields?

2024-02-05 06:04 UTC, captain2b commented on packages/ketcher-core/src/domain/entities/BaseMicromoleculeEntity.ts
> +  initiallySelected?: boolean | 'invalid';
No, because i need it to be in the entities interfaces (atom, bond,etc)

2024-02-05 13:23 UTC, rrodionov91 commented on packages/ketcher-react/src/script/ui/state/shared.ts
> +          value.getInitiallySelected()
probably we can use value.getInitiallySelected?.() here

2024-02-06 10:21 UTC, Zhirnoff approved these changes

2024-02-06 10:34 UTC, merged