Autotests: #1234 - missed smarts tests
epam/ketcher pull request #4021
Opened 2024-02-03 12:09 UTC by Zhirnoff

## How the feature works? / How did you fix the issue?
(Screenshots, videos, or GIFs, if applicable)

## Check list
- [ ] unit-tests written
- [ ] e2e-tests written
- [ ] documentation updated
- [x] PR name follows the pattern `#1234 – issue name`
- [x] branch name doesn't contain '#'
- [ ] PR is linked with the issue
- [x] base branch (master or release/xx) is correct
- [ ] task status changed to "Code review"
- [ ] reviewers are notified about the pull request

2024-02-03 12:13 UTC, Zhirnoff commented
Cherry-picked from https://github.com/epam/ketcher/pull/3834

2024-02-05 13:29 UTC, rrodionov91 requested changes

2024-02-05 13:29 UTC, rrodionov91 commented on ketcher-autotests/tests/File-Management/SMARTS-Files/smarts-files.spec.ts
> +    Screenshot for this test is incorrect since Indigo issue #1332 still occurs when test is running locally
Issue https://github.com/epam/indigo/issues/1332 already closed. I think this comment is not valid anymore

2024-02-05 13:29 UTC, rrodionov91 commented on ketcher-autotests/tests/User-Interface/Editing-Tools/Copy-Cut-Paste/copy-cut-paste.spec.ts-snapshots/Copy-Cut-Paste-Actions-Paste-structure-as-SMARTS-with-ctrl-alt-V-keyboard-shortcut-1-chromium-linux.png
Why this error appears?

2024-02-05 17:39 UTC, merged