Macro: #3923 - The scale of structures in "Select Attachment Points" Modal is too big
epam/ketcher pull request #4059
Opened 2024-02-08 10:41 UTC by StarlaStarla

## How the feature works? / How did you fix the issue?
(Screenshots, videos, or GIFs, if applicable)

## Check list
- [ ] unit-tests written
- [ ] e2e-tests written
- [ ] documentation updated
- [ ] PR name follows the pattern `#1234 – issue name`
- [ ] branch name doesn't contain '#'
- [ ] PR is linked with the issue
- [ ] base branch (master or release/xx) is correct
- [ ] task status changed to "Code review"
- [ ] reviewers are notified about the pull request

2024-02-08 16:42 UTC, rrodionov91 requested changes

2024-02-08 16:42 UTC, rrodionov91 commented on packages/ketcher-core/src/application/render/renderStruct.ts
> +    monomerConnectionMode = false,
I would propose to rename it to something more common, like needRescale or somethingLike that

2024-02-09 11:12 UTC, ilya-asiyuk-epam approved these changes

2024-02-27 09:40 UTC, ilya-asiyuk-epam approved these changes

2026-05-31 13:52 UTC, AlexeyGirin commented
@copilot resolve the merge conflicts in this pull request

2026-05-31 14:27 UTC, AlexeyGirin commented
@copilot resolve the merge conflicts in this pull request

2026-05-31 15:03 UTC, AlexeyGirin commented
@copilot resolve the merge conflicts in this pull request

2026-05-31 18:44 UTC, AlexeyGirin commented
@copilot resolve the merge conflicts in this pull request

2026-06-05 12:43 UTC, closed without merging