#64 Implement ability to save structures with stereo marks
epam/ketcher pull request #416
Opened 2021-03-22 11:57 UTC by irinatelnova

2021-03-24 13:49 UTC, ensemenova approved these changes

2021-03-25 10:56 UTC, TomasLight requested changes

2021-03-25 10:56 UTC, TomasLight commented on packages/ketcher-react/src/script/ui/views/toolbars/BottomToolbar/BottomToolbar.tsx
> +        )}
process.env is forbidden to use in web

2021-03-25 11:00 UTC, TomasLight approved these changes

2021-03-25 13:52 UTC, AndreiMazol approved these changes

2021-03-25 13:52 UTC, merged