#3775 - Phenylalanine mustard is displayed incorrectly in the Structure library
epam/ketcher pull request #4270
Opened 2024-03-19 11:23 UTC by baranovdv

- fix library.sdf phenylalanine mustard description

## How the feature works? / How did you fix the issue?
(Screenshots, videos, or GIFs, if applicable)

## Check list
- [ ] unit-tests written
- [ ] e2e-tests written
- [ ] documentation updated
- [x] PR name follows the pattern `#1234 – issue name`
- [x] branch name doesn't contain '#'
- [ ] PR is linked with the issue
- [x] base branch (master or release/xx) is correct
- [ ] task status changed to "Code review"
- [ ] reviewers are notified about the pull request

2024-03-21 19:21 UTC, rrodionov91 requested changes

2024-03-21 19:21 UTC, rrodionov91 commented on ketcher-autotests/tests/Templates/Template-Library/template-library.spec.ts-snapshots/Templates---Template-Library-Template-with-chiral-flag-0-with-ignoreChiralFlag-enabled-disabled-1-chromium-linux.png
I believe it should look like this
<img width="308" alt="image" src="https://github.com/epam/ketcher/assets/14859362/b488a92c-c375-42f8-9946-4b46c3c9de12">

Please clarify the correctness of structure

2024-03-21 20:46 UTC, baranovdv commented on ketcher-autotests/tests/Templates/Template-Library/template-library.spec.ts-snapshots/Templates---Template-Library-Template-with-chiral-flag-0-with-ignoreChiralFlag-enabled-disabled-1-chromium-linux.png
Updated structure:

<img width="296" alt="Снимок экрана 2024-03-22 в 01 37 45" src="https://github.com/epam/ketcher/assets/117748331/f58bff77-16c8-4208-a965-46855acfc423">

from here:
https://pubchem.ncbi.nlm.nih.gov/substance/374913453

Looks better

2024-03-22 08:18 UTC, NataliaLoginova approved these changes

2024-03-22 12:55 UTC, baranovdv commented on ketcher-autotests/tests/Templates/Template-Library/template-library.spec.ts-snapshots/Templates---Template-Library-Template-with-chiral-flag-0-with-ignoreChiralFlag-enabled-disabled-1-chromium-linux.png
updated to such structure:
<img width="285" alt="Снимок экрана 2024-03-22 в 17 54 39" src="https://github.com/epam/ketcher/assets/117748331/6b880dec-1a07-4a90-bc54-fa944d154a98">

according to Olga Nazarenko recommendation

2024-03-22 13:38 UTC, baranovdv commented on ketcher-autotests/tests/Templates/Template-Library/template-library.spec.ts-snapshots/Templates---Template-Library-Template-with-chiral-flag-0-with-ignoreChiralFlag-enabled-disabled-1-chromium-linux.png
new update from Olga Nazarenko:
<img width="220" alt="Снимок экрана 2024-03-22 в 18 37 44" src="https://github.com/epam/ketcher/assets/117748331/05a33471-6b55-46ed-9355-9d3bf1374e69">

2024-03-22 15:20 UTC, rrodionov91 approved these changes

2024-03-22 18:18 UTC, merged