#4369 - Del button works as Backspace button that is wrong
epam/ketcher pull request #4408
Opened 2024-04-04 10:54 UTC by burcinkarimov

## How the feature works? / How did you fix the issue?
Backspace and Delete keys both had the same deletion behavior (deleting left node). Since Delete key should remove the right side, according changes were applied to separate their behavior. 

## Check list
- [ ] unit-tests written
- [ ] e2e-tests written
- [ ] documentation updated
- [x] PR name follows the pattern `#1234 – issue name`
- [x] branch name doesn't contain '#'
- [x] PR is linked with the issue
- [ ] base branch (master or release/xx) is correct
- [ ] task status changed to "Code review"
- [ ] reviewers are notified about the pull request

2024-04-08 14:52 UTC, rrodionov91 requested changes

2024-04-08 14:52 UTC, rrodionov91 commented on packages/ketcher-core/src/application/editor/modes/SequenceMode.ts
Looks like this change causes bug found by autotest. I believe we need to fix it here instead of update screenshot.

2024-04-08 14:52 UTC, rrodionov91 commented on packages/ketcher-core/src/application/editor/modes/SequenceMode.ts
> +    const deleteNode = (direction: 'left' | 'right') => {
I would propose to use enum instead of string literal type to modify it easier in future

2024-04-15 12:22 UTC, rrodionov91 approved these changes

2024-04-15 18:52 UTC, NataliaLoginova approved these changes

2024-04-15 18:52 UTC, merged