#4380 – Macro: Display IDT aliases in monomer library
epam/ketcher pull request #4591
Opened 2024-05-08 17:02 UTC by DmitriiP-EPAM

## How the feature works? / How did you fix the issue?
(Screenshots, videos, or GIFs, if applicable)
<img width="262" alt="Снимок экрана 2024-05-21 в 16 31 35" src="https://github.com/epam/ketcher/assets/167520099/64945ea0-6b8d-4d6e-9dd1-618062077ee8">
<img width="270" alt="Снимок экрана 2024-05-21 в 16 33 08" src="https://github.com/epam/ketcher/assets/167520099/2d250999-b620-4484-a6b9-4104c2fe35a5">

## Check list
- [x] unit-tests written
- [ ] e2e-tests written
- [ ] documentation updated
- [x] PR name follows the pattern `#1234 – issue name`
- [x] branch name doesn't contain '#'
- [x] PR is linked with the issue
- [x] base branch (master or release/xx) is correct
- [ ] task status changed to "Code review"
- [ ] reviewers are notified about the pull request

2024-05-23 22:03 UTC, NataliaLoginova requested changes

2024-05-23 22:03 UTC, NataliaLoginova commented on packages/ketcher-macromolecules/src/components/monomerLibrary/monomerLibraryGroup/MonomerGroup.tsx
> +    const style = { right: '-88px', top };
try to avoid custom styles with magic numbers

2024-05-31 15:14 UTC, rrodionov91 approved these changes

2024-05-31 18:25 UTC, rrodionov91 approved these changes

2024-05-31 18:26 UTC, NataliaLoginova approved these changes

2024-05-31 18:27 UTC, merged