#4833 - Support rendering multiple ketcher editors on a page without an iframe
epam/ketcher pull request #4834
Opened 2024-06-12 16:10 UTC by ihuang8

## How the feature works? / How did you fix the issue?
(Screenshots, videos, or GIFs, if applicable)

Add a ketcherId so that multiple ketcher instances can be added to the same page without using an iframe. Instead of binding each ketcher instance to the iframe, they can now be stored in the React state and easily accessed to obtain the data. 

## Check list
- [ ] unit-tests written
- [ ] e2e-tests written
- [ ] documentation updated
- [ ] PR name follows the pattern `#1234 – issue name`
- [ ] branch name doesn't contain '#'
- [ ] PR is linked with the issue
- [ ] base branch (master or release/xx) is correct
- [ ] task status changed to "Code review"
- [ ] reviewers are notified about the pull request

2024-06-13 11:18 UTC, rrodionov91 requested changes

2024-06-13 11:18 UTC, rrodionov91 commented on packages/ketcher-react/src/constants.ts
> +  `ketcher-init-${ketcherId}`;
Could you please make it backward-compatible by using old 'ketcher-init' id by default?

2024-06-18 19:57 UTC, ihuang8 commented
@rrodionov91 Is there anything else you need from me here?

2024-06-19 13:52 UTC, rrodionov91 approved these changes

2024-06-19 14:59 UTC, merged

2024-06-19 15:02 UTC, rrodionov91 commented
Hi @ihuang8 
Thank you for fixing this issue.
Really appreciate it.