#4962 - Bond tool and Erase tool buttons have to be disabled in Sequeince mode (since they are not applicable)
epam/ketcher pull request #5020
Opened 2024-07-05 18:00 UTC by Guch1g0v

## How the feature works? / How did you fix the issue?
(Screenshots, videos, or GIFs, if applicable)

## Check list
- [ ] unit-tests written
- [ ] e2e-tests written
- [ ] documentation updated
- [ ] PR name follows the pattern `#1234 – issue name`
- [ ] branch name doesn't contain '#'
- [ ] PR is linked with the issue
- [ ] base branch (master or release/xx) is correct
- [ ] task status changed to "Code review"
- [ ] reviewers are notified about the pull request

2024-07-06 13:09 UTC, rrodionov91 requested changes

2024-07-06 13:09 UTC, rrodionov91 commented on packages/ketcher-macromolecules/src/components/LeftMenuComponent/LeftMenuComponent.tsx
> +  const isSequenceMode = useLayoutMode() === 'sequence-layout-mode';
Please use constant ModeTypes here.

2024-07-06 18:40 UTC, rrodionov91 approved these changes

2024-07-06 18:40 UTC, rrodionov91 requested changes
Please fix failed tests

2024-07-07 07:09 UTC, AlexeyGirin approved these changes
Approved

2024-07-07 10:06 UTC, rrodionov91 requested changes

2024-07-07 10:06 UTC, rrodionov91 commented on ketcher-autotests/tests/Macromolecule-editor/Sequence-Mode/sequence-mode-selection.spec.ts
> +  test('Select a nucleotide or a group of nucleotides, then click in the middle of the screen. Confirm that selection is cleared.', async ({
The name of test was changed, so it now generates screenshots with new name. Please delete old screenshots then.

2024-07-07 10:38 UTC, rrodionov91 approved these changes

2024-07-07 13:21 UTC, merged