#339 expand text tool
epam/ketcher pull request #504
Opened 2021-05-07 17:38 UTC by irinatelnova

2021-05-13 06:44 UTC, MagomedGasanov commented on packages/ketcher-react/src/script/ui/views/components/Dialog/Dialog.tsx
> +  manageFocus?: boolean
I think name 'manageFocus' is more appropriate for the function than for boolean type

2021-05-14 13:10 UTC, AndreiMazol requested changes
You must not use UI specific library in core package

2021-05-14 13:47 UTC, AndreiMazol requested changes

2021-05-14 13:47 UTC, AndreiMazol commented on packages/ketcher-core/src/chemistry/entities/Text.ts
> +import { RawDraftContentState } from 'draft-js'
Please remove 'draft-js' dependency from core package

2021-05-14 13:47 UTC, AndreiMazol commented on packages/ketcher-core/src/chemistry/entities/Text.ts
> +  rawContent: RawDraftContentState
Please rename it to label or content

2021-05-14 13:47 UTC, AndreiMazol commented on packages/ketcher-core/src/chemistry/entities/Text.ts
>    type: string
What do you need 'type' property for?

2021-05-14 13:47 UTC, AndreiMazol commented on packages/ketcher-react/src/script/editor/tool/text.ts
> +import _ from 'lodash'
Please import single lodash function instead

2021-05-14 13:47 UTC, AndreiMazol commented on packages/ketcher-react/src/script/render/restruct/ReText.ts
> +import { TextStyle } from '../../ui/views/modal/components/Text/components/TextControlPanel'
It looks strange

2021-05-14 13:47 UTC, AndreiMazol commented on packages/ketcher-react/src/script/render/restruct/ReText.ts
> +    this.item.rawContent.blocks.forEach((block: RawDraftContentBlock) => {
Potentially exception can be thrown here

2021-05-14 13:47 UTC, AndreiMazol commented on packages/ketcher-react/src/script/render/restruct/ReText.ts
> +import _ from 'lodash'
Please import single lodash function instead

2021-05-14 13:47 UTC, AndreiMazol commented on packages/ketcher-react/src/script/render/restruct/ReText.ts
> +  getRanges(
Please follow SOLID principles. This object has lots of responsibilities

2021-05-14 13:47 UTC, AndreiMazol commented on packages/ketcher-react/src/script/ui/views/components/Dialog/Dialog.tsx
> +    if (manageFocus === false) return
It looks strange

2021-05-27 15:35 UTC, closed without merging