#4926-Add IDT alias to chem monomer
epam/ketcher pull request #5286
Opened 2024-08-13 17:39 UTC by KristinaKasyanovskaya

Issue => https://github.com/epam/ketcher/issues/4926

- [x] Add IDT alias [/3ThioMC3-D/](https://www.idtdna.com/site/Catalog/Modifications/Product/1460) to monomer SS3 (Dipropanol-disulfide)

## Check list
- [ ] unit-tests written
- [ ] e2e-tests written
- [ ] documentation updated
- [x] PR name follows the pattern `#1234 – issue name`
- [x] branch name doesn't contain '#'
- [x] PR is linked with the issue
- [x] base branch (master or release/xx) is correct
- [x] task status changed to "Code review"
- [x] reviewers are notified about the pull request

2024-08-14 08:36 UTC, NataliaLoginova approved these changes

2024-08-19 13:54 UTC, rrodionov91 requested changes

2024-08-19 13:54 UTC, rrodionov91 commented on packages/ketcher-core/src/application/editor/data/monomers.ket
> +  },
1) This monomer has only third position alias. Please set this object:
```
"idtAliases": {
      "base": "ThioMC3-D",
      "modifications": {
        "endpoint3": "3ThioMC3-D",
      }
    },
```

2) Please correct formatting (I mean tabs)

2024-08-20 09:41 UTC, rrodionov91 approved these changes

2024-08-20 09:42 UTC, merged