527 Implement "Enhanced Stereochemistry" window
epam/ketcher pull request #558
Opened 2021-06-02 06:44 UTC by MagomedGasanov

2021-06-03 08:56 UTC, AndreiMazol requested changes
Please update PR based on our discussion

2021-06-03 08:56 UTC, AndreiMazol commented on packages/ketcher-react/src/script/ui/dialog/toolbox/enhancedStereo.tsx
> +  struct: any
use Struct please

2021-06-03 08:56 UTC, AndreiMazol commented on packages/ketcher-react/src/script/ui/data/convert/structconv.js
> +  const initOrNumber = 1
I guess it can be moved to Constants

2021-06-04 09:43 UTC, MagomedGasanov commented on packages/ketcher-react/src/script/ui/dialog/toolbox/enhancedStereo.tsx
> +  struct: any
Done!

2021-06-04 09:44 UTC, MagomedGasanov commented on packages/ketcher-react/src/script/ui/data/convert/structconv.js
> +  const initOrNumber = 1
Done!

2021-06-07 08:11 UTC, AndreiMazol approved these changes

2021-06-07 08:11 UTC, merged