#5370 – System should remember the canvas mode on Molecules/Macromolecules mode switch (do not switch to Sequernce by default)
epam/ketcher pull request #5631
Opened 2024-10-03 12:28 UTC by mnmsvlw

## How the feature works? / How did you fix the issue?
A new parameter has been added to the editor state, which stores the macromolecules mode that was active at the moment of switching back from macromolecules to molecules. This state is used for the initial mode selection in `useLayoutHook`

## Check list
- [ ] unit-tests written
- [ ] e2e-tests written
- [ ] documentation updated
- [x] PR name follows the pattern `#1234 – issue name`
- [x] branch name doesn't contain '#'
- [x] PR is linked with the issue
- [x] base branch (master or release/xx) is correct
- [x] task status changed to "Code review"
- [x] reviewers are notified about the pull request

2024-10-18 21:46 UTC, NataliaLoginova approved these changes

2024-10-19 08:21 UTC, Zhirnoff requested changes

2024-10-19 08:21 UTC, Zhirnoff commented on ketcher-autotests/tests/Macromolecule-editor/Macro-Micro-Switcher/macro-micro-switcher.spec.ts-snapshots/Macro-Micro-Switcher-Check-that-it-is-not-poss-5053b-tween-monomer-and-micromolecule-in-micro-mode-1-chromium-linux.png
In my opinion, the new screenshot is incorrect because in the previous screenshot, a bond was highlighted, but in the new one, a double bond appeared.

2024-10-19 08:21 UTC, Zhirnoff commented on ketcher-autotests/tests/Macromolecule-editor/Macro-Micro-Switcher/macro-micro-switcher.spec.ts-snapshots/Macro-Micro-Switcher-Delete-bond-between-micro-ece7d-oint-and-CHEM-in-micro-mode-and-Undo-deletion-1-chromium-linux.png
Same thing with screenshot

2024-10-21 12:22 UTC, mnmsvlw commented on ketcher-autotests/tests/Macromolecule-editor/Macro-Micro-Switcher/macro-micro-switcher.spec.ts-snapshots/Macro-Micro-Switcher-Check-that-it-is-not-poss-5053b-tween-monomer-and-micromolecule-in-micro-mode-1-chromium-linux.png
The issue was that the test was performing actions based on coordinates, and since the layout on the canvas changed, the test couldn't target the correct bond. I updated the tests and screenshots

2024-10-21 13:01 UTC, Zhirnoff approved these changes

2024-10-22 10:10 UTC, merged