#418 stereo flags shouldnt appear for structures without correct stereocenters
epam/ketcher pull request #597
Opened 2021-06-17 11:18 UTC by MagomedGasanov

2021-07-05 10:00 UTC, AleksandrPokrovskii commented on packages/ketcher-react/src/script/editor/actions/bond.ts
> +function getStereoParity(stereo) {
add types for function

2021-07-05 10:07 UTC, AleksandrPokrovskii approved these changes

2021-07-05 11:26 UTC, MagomedGasanov commented on packages/ketcher-react/src/script/editor/actions/bond.ts
> +function getStereoParity(stereo) {
Done

2021-07-05 13:45 UTC, AndreiMazol requested changes
ImplicitH should be calculated by Struct object.  Please add an additional operation to trigger recalculation instead of setting implicitH directly.

2021-07-06 15:18 UTC, AndreiMazol approved these changes

2021-07-06 15:18 UTC, merged