#4526 - In the Text-editing mode, the canvas is not moved to make the newly added sequence visible
epam/ketcher pull request #6224
Opened 2024-12-27 18:55 UTC by kostrubin

## How the feature works? / How did you fix the issue?
Added check if the element’s height is more than window height and automatic scrolling if true.

## Check list
- [ ] unit-tests written
- [ ] e2e-tests written
- [ ] documentation updated
- [ ] PR name follows the pattern `#1234 – issue name`
- [ ] branch name doesn't contain '#'
- [ ] PR is linked with the issue
- [ ] base branch (master or release/xx) is correct
- [ ] task status changed to "Code review"
- [ ] reviewers are notified about the pull request

2024-12-27 22:16 UTC, NataliaLoginova approved these changes

2024-12-31 10:36 UTC, Zhirnoff requested changes

2024-12-31 10:36 UTC, Zhirnoff commented on ketcher-autotests/tests/Macromolecule-editor/Sequence-Mode/sequence-mode-selection.spec.ts-snapshots/Sequence-mode-selection-for-edit-mode-Select-letters-with-Shift-ArrowLeft-then-delete-and-undo-1-chromium-linux.png
The tooltips have appeared on the screenshot. They shouldn't be there, as they will cause the tests to be flaky.

2024-12-31 10:36 UTC, Zhirnoff commented on ketcher-autotests/tests/Macromolecule-editor/Sequence-Mode/sequence-mode-selection.spec.ts-snapshots/Sequence-mode-selection-for-edit-mode-Select-letters-with-Shift-ArrowRight-button-1-chromium-linux.png
The tooltips have appeared on the screenshot. They shouldn't be there, as they will cause the tests to be flaky.

2024-12-31 11:06 UTC, Zhirnoff approved these changes

2024-12-31 11:36 UTC, merged