#5700 - System allow to establish infinit number of bonds from monomer to microstructure
epam/ketcher pull request #6225
Opened 2024-12-28 22:45 UTC by lmhs

## How the feature works? / How did you fix the issue?
When new bond is being created from the same attachment point, previously created bond from the same attachment point is not removed, only firstAttachmentPoint is being removed and assigned to a new node.

TODO:
undo/redo operations support

## Check list
- [ ] unit-tests written
- [ ] e2e-tests written
- [ ] documentation updated
- [x] PR name follows the pattern `#1234 – issue name`
- [x] branch name doesn't contain '#'
- [x] PR is linked with the issue
- [x] base branch (master or release/xx) is correct
- [ ] task status changed to "Code review"
- [ ] reviewers are notified about the pull request

2025-02-16 19:07 UTC, NataliaLoginova approved these changes

2025-02-18 12:20 UTC, rrodionov91 requested changes

2025-02-18 12:20 UTC, rrodionov91 commented on packages/ketcher-core/src/application/editor/tools/Bond.ts
> +      monomer instanceof Chem &&
Please delete ```monomer instanceof Chem &&``` because restriction should work for all types of monomers

2025-02-18 12:20 UTC, rrodionov91 commented on ketcher-autotests/tests/Macromolecule-editor/Polymer-Bond-Tool/connection-rules-for-chems-monomers.spec.ts
> -      test(`Case 11: Connect Center of Chem(${leftMonomer.alias}) to atom of MicroMolecule(${rightMolecule.alias})`, async () => {
If we deleted tests, then please delete screenshots related to it

2025-02-18 12:28 UTC, ALexanderSPB commented on packages/ketcher-core/src/application/editor/tools/Bond.ts
> +      monomer instanceof Chem &&
<img width="885" alt="image" src="https://github.com/user-attachments/assets/c20b7933-3474-4075-87de-1944a6595e56" />

2025-02-18 13:27 UTC, rrodionov91 commented on packages/ketcher-core/src/application/editor/tools/Bond.ts
> +      monomer instanceof Chem &&
I saw the description.
I'm 100% sure that it should work for every type of monomer. Discussed with @AlexeyGirin one more time, he approved. Please remove the line.

2025-02-19 14:16 UTC, lmhs commented on packages/ketcher-core/src/application/editor/tools/Bond.ts
> +        'CHEM monomer to Atom supports only attachment points for bond creation',
if new rule is applied not just for CHEM monomers, then please update this message

2025-02-20 10:08 UTC, ALexanderSPB commented on packages/ketcher-core/src/application/editor/tools/Bond.ts
> +        'CHEM monomer to Atom supports only attachment points for bond creation',
Updated

2025-02-20 10:08 UTC, ALexanderSPB commented on ketcher-autotests/tests/Macromolecule-editor/Polymer-Bond-Tool/connection-rules-for-chems-monomers.spec.ts
> -      test(`Case 11: Connect Center of Chem(${leftMonomer.alias}) to atom of MicroMolecule(${rightMolecule.alias})`, async () => {
Deleted

2025-02-20 13:43 UTC, rrodionov91 approved these changes

2025-02-20 13:45 UTC, merged