#723 Structure with some S-groups cannot be opened
epam/ketcher pull request #727
Opened 2021-08-24 12:48 UTC by AndreiProkofev

2021-08-24 12:50 UTC, AndreiProkofev commented on packages/ketcher-react/src/script/ui/state/shared.js
> +          if (!err.isSGroupError) {
The only change in this file. Other stuff is just code styling from prettier

2021-08-24 12:59 UTC, AndreiMazol requested changes
Confirm dialog should be shown once even if file contains a lots of unsupported S-groups

2021-08-25 09:44 UTC, AndreiProkofev commented on packages/ketcher-react/src/script/ui/state/shared.js
> +          if (!err.isSGroupError) {
Deprecated

2021-08-25 11:34 UTC, closed without merging

2021-08-25 11:36 UTC, AndreiProkofev commented
PR closed due to migration of the solution to release 2.3.1