#954 Redesign the floating windows - Attachment Point Tool
epam/ketcher pull request #977
Opened 2021-11-16 09:28 UTC by r1z3rISGOD

2021-11-16 12:03 UTC, dmitrii-kliushentsev approved these changes

2021-11-17 08:56 UTC, AndreiMazol commented on packages/ketcher-react/src/script/ui/views/modal/components/toolbox/Attach/Attach.tsx
> +      title="ATTACHMENT POINTS"
It would be better to  use text  transform instead

2021-11-17 08:57 UTC, AndreiMazol commented on packages/ketcher-react/src/Editor.module.less
> +    margin-top: 1px \9; // IE8-9
What do you need it for? IE8-9 are OOS

2021-11-17 08:59 UTC, AndreiMazol requested changes
see comments

2021-11-18 10:17 UTC, AndreiMazol approved these changes

2021-11-18 10:17 UTC, merged