#39 atom generics are replaced with r# in daylight smiles
epam/ketcher pull request #979
Opened 2021-11-17 07:59 UTC by ViktoriiaFedotkina

2021-11-17 08:53 UTC, AndreiMazol requested changes
Please update warning message

2021-11-18 19:17 UTC, r1z3rISGOD approved these changes

2021-11-19 07:17 UTC, dmitrii-kliushentsev approved these changes

2021-11-19 08:57 UTC, ElenaOdnoshivkina approved these changes

2021-11-19 13:39 UTC, AnaMoskvina approved these changes

2021-11-22 12:32 UTC, AndreiMazol approved these changes

2021-11-22 12:32 UTC, merged