#961 Error window is shown when user apply 3D to empty canvas
epam/ketcher pull request #982
Opened 2021-11-17 20:25 UTC by ElenaOdnoshivkina

2021-11-18 09:53 UTC, r1z3rISGOD approved these changes

2021-11-18 10:14 UTC, AndreiMazol requested changes
PR should be updated: some changes are not relevant

2021-11-19 07:14 UTC, dmitrii-kliushentsev approved these changes

2021-11-19 14:02 UTC, AnaMoskvina approved these changes

2021-11-22 08:02 UTC, AndreiMazol approved these changes

2021-11-22 08:02 UTC, merged