#513 It should be impossible to add attachment point(s) to an atom with R-Group Label and vice versa
epam/ketcher pull request #983
Opened 2021-11-18 07:20 UTC by ElenaOdnoshivkina

2021-11-18 09:59 UTC, r1z3rISGOD approved these changes

2021-11-18 10:12 UTC, AndreiMazol requested changes
need to discuss

2021-11-18 18:48 UTC, AnaMoskvina commented on packages/ketcher-react/src/script/editor/tool/rgroupatom.js
> +  const struct = this.editor.render.ctab.molecule
it might be nice to move this part into common util function, and reuse it, if possible

2021-11-18 18:48 UTC, AnaMoskvina approved these changes

2021-11-19 07:13 UTC, dmitrii-kliushentsev approved these changes

2021-11-19 11:15 UTC, ViktoriiaFedotkina approved these changes

2021-11-22 08:05 UTC, AndreiMazol approved these changes

2021-11-22 08:05 UTC, merged